CSOK/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSOK.Models
{
    public class Question
    {
        public int ID { get; set; }
        //[Required(ErrorMessage = "Please enter a title")]
        public string Title { get; set; } // тема
        [Required(ErrorMessage = "Please enter a body")]
        public string Body { get; set; } // тело вопроса
        public virtual User Author { get; set; }
        //public int AuthorID { get; set; }
        public bool HasPossibleAnswer { get; set; } // тип ответа
        // public bool CheckBoxOrRadioAnswer { get; set; }//
        public bool HasExcessBlocks { get; set; }
        public bool CheckBoxAnswer { get; set; }//
        public bool RadioAnswer { get; set; }
        public bool MatrixAnswer { get; set; }//ответ внутрь полей матрицы
        [NotMapped]
        public string SelectedRadio { get; set; }// поле для radiobutton в базе не отображается
        public bool isSelected { get; set; }
        public string Tag { get; set; }
        public DateTime CreationDataTime { get; set; }
        public float difficulty { get; set; }
        public virtual CorrectAnswer CorrectAnswer { get; set; }
        //public virtual List<Answer> Answers { get; set; }
        public virtual List<PossibleAnswer> PossibleAnswers { get; set; }
        public virtual List<Image> Images { get; set; }
        public virtual List<Matrix> Matrices { get; set; }
        public virtual List<Block> Blocks { get; set; }
        public virtual List<Excess_Block> Excess_Blocks { get; set; }
        public virtual List<TestItem> TestItems { get; set; }
        public virtual List<TestItemAnswer> TestItemAnswers { get; set; }
        public virtual Theme Theme { get; set; }
        public Question()
        {
            Images = new List<Image>();
            PossibleAnswers = new List<PossibleAnswer>();
            //Answers = new List<Answer>();
            Blocks = new List<Block>();
            Excess_Blocks = new List<Excess_Block>();
            TestItems = new List<TestItem>();
            TestItemAnswers = new List<TestItemAnswer>();
        }
    }

    public class QuestionsIndex
    {
        public int ID { get; set; }
        [Display(Name = "Тема")]
        public string Title { get; set; }
        [Display(Name = "Вопрос")]
        public string Body { get; set; }
        [Display(Name = "Дата создания")]
        public DateTime CreationDataTime { get; set; }
        [Display(Name = "Кол-во ответов")]
        public int AnswCount { get; set; }
        [Display(Name = "Блоки")]
        public IEnumerable<string> BlockBody { get; set; }
        public IEnumerable<string> ExcessBlockBody { get; set; }
        [Display(Name = "Изображение")]
        public IEnumerable<int> ImageId { get; set; }
        [Display(Name = "Матрица")]
        public Matrix Matrix { get; set; }
        public List<PossibleAnswer> PossibleAnswers { get; set; }
        public bool CheckBoxAnswer { get; set; }//
        public bool RadioAnswer { get; set; }
        public CorrectAnswer CorrectAnswer { get; set; }
        public bool HasPossibleAnswer { get; set; }
        //public List<List<string>> Des_matrix { get; set; }

    }

    public class CorrectAnswer
    {
        [Key]
        [ForeignKey("Question")]
        public int QuestionID { get; set; }
       
        public string Body { get; set; }
        public virtual Question Question { get; set; }
        public virtual List<AnswerCorrectAnswer> AnswerCorrectAnswers { get; set; }
        public CorrectAnswer() {
            AnswerCorrectAnswers = new List<AnswerCorrectAnswer>();

        }

    }

    public class PossibleAnswer
    {
        public int ID { get; set; }
        public string Body { get; set; }
        public Boolean IsRight { get; set; }
        public virtual List<AnswerPossibleAnswer> AnswerPossibleAnswers { get; set; }
        public virtual Question Question { get; set; }
        public PossibleAnswer() {
            AnswerPossibleAnswers = new List<AnswerPossibleAnswer>();
        }
    }
}

CSOK/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSOK.Models;
using System.IO;
using System.Data.Entity;
using System.Data;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using WebMatrix.WebData;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;


namespace CSOK.Controllers
{
    [Authorize]
    [Authorize(Roles = "Teacher")]
    public class QuestionsController : Controller
    {
        private MyDbContext db = new MyDbContext();
        private UsersContext dbu = new UsersContext();
        //
        // GET: /Question/

        public ActionResult Index()
        {
            //List<int> guids = db.Images.Select(img => img.Question.ID).ToList();
            IEnumerable<QuestionsIndex> query = (from q in db.Questions
                                                 select new QuestionsIndex { ID = q.ID, Title = q.Title, Body = q.Body, CreationDataTime = q.CreationDataTime, ImageId = q.Images.Select(ids => ids.ImageId) }).ToList();

            /*foreach (var q in query)
            { 
                q.AnswCount = (from a in db.Answers
                               where (a.Question.ID==q.ID)
                               select a).Count();
                 
            }*/
            return View(query);
        }

        //
        // GET: /Questions/Details/5

        public PartialViewResult Details(int id = 0)
        {
            Question _question = db.Questions.First(q => q.ID == id);
            // _question.Author = db.UserProfiles.First(a => a.UserId == _question.Author.UserId);
            //logger.Info(db.Questions.First(q => q.ID == id).Author.UserName);
            //  List<Answer> _answers = (from a in db.Answers
            //                      where (a.Question.ID == id)
            //                select a).ToList();
            /*  if (_question == null)
              {
                  return HttpNotFound();
              }*/

            // QuestionAndAnswers qa = new QuestionAndAnswers { Question = _question, Answers = _answers };
            QuestionsIndex QI = new QuestionsIndex
            {
                ID = _question.ID,
                Title = _question.Title,
                Body = HttpUtility.HtmlDecode(_question.Body),
                ImageId = _question.Images.Select(ids => ids.ImageId),
                PossibleAnswers = _question.PossibleAnswers,
                CheckBoxAnswer = _question.CheckBoxAnswer,
                RadioAnswer = _question.RadioAnswer,
                HasPossibleAnswer = _question.HasPossibleAnswer,
                CorrectAnswer = _question.CorrectAnswer,
                BlockBody = _question.Blocks.Select(b => b.Body),
                ExcessBlockBody = _question.Excess_Blocks.Select(b=>b.Body),
                Matrix = _question.Matrices.SingleOrDefault(m => m.Question.ID == id)
            };
            if (QI.Matrix != null)
            {
                ViewBag.result = OutputMatrix(QI.Matrix.Matrix_Id) as List<List<string>>;
            }

            return PartialView("Details", QI);
        }
        [HttpGet]
        public JsonResult GetThemes()
        {
            var lst = (from t in db.Themes select new { t.Id, t.Name, StructureId = t.Structure.Id });
            List<object> themes = new List<object>();
            foreach (var th in lst)
            {
                themes.Add(th);
            }
            return Json(themes, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            //ViewBag.structs = new SelectList(db.Structures.ToList(), "Id", "Name");
            if(db.Structures.ToList().Count() != 0 ) ViewBag.structs = db.Structures.ToList();
            return View();
        }

        //
        // POST: /Question/Create
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Question question, List<string> answ, string answrad, HttpPostedFileBase[] files, List<bool> CorrAnsw, string[] checkedValues, int theme_id)
        {
            bool ch = ((CorrAnsw[0] == true) == (question.CorrectAnswer.Body != null)) && ((CorrAnsw[0] == false) == (question.CorrectAnswer.Body == null));
            bool chform = (question.HasPossibleAnswer != false) || (CorrAnsw[0] != false);
            bool chradORbox = (question.HasPossibleAnswer == false) || ((question.HasPossibleAnswer == true) && ((question.RadioAnswer != false) || (question.CheckBoxAnswer != false)));
            //question.Body = str_body.Replace(@"&amp;", "&").Replace(@"&gt;", ">").Replace(@"&lt;", "<").Replace(@"&#39;", "'").Replace(@"&quot;", "\"");
            string description = HttpUtility.HtmlEncode(question.Body);
            question.Body = description;
            if (db.Structures.ToList().Count() != 0) ViewBag.structs = db.Structures.ToList();
            var th = db.Themes.Find(theme_id);
            question.Title = th.Name;
            question.Theme = th;
            if (ModelState.IsValid && ch && chform && chradORbox)
            {

                //int currentID = WebSecurity.CurrentUserId;
                //User currentAuthor = dbu.Users.Find(WebSecurity.CurrentUserId);
                question.CreationDataTime = System.DateTime.Now;
                question.Author = db.User.Find(WebSecurity.CurrentUserId);
                if (!question.HasPossibleAnswer)
                {
                    question.PossibleAnswers.Clear();
                }
                else
                {
                    question.CorrectAnswer = null;
                    int l = answ.Count;
                    bool[] answRight = new bool[l];

                    if (answrad != null)//занесение в массив правильного номера raduobutton
                    {
                        for (int i = 0; i < l; i++)
                        {
                            answRight[i] = false;
                        }
                        int a = Convert.ToInt32(answrad);
                        answRight[a] = true;
                    }

                    if (checkedValues != null)//занесение в массив отмеченных checkbox
                    {
                        for (int i = 0; i < l; i++)
                        {
                            answRight[i] = false;
                        }
                        foreach (string checkedValue in checkedValues)
                        {
                            int a = Convert.ToInt32(checkedValue);
                            answRight[a] = true;

                        }

                    }
                    for (int i = 0; i < answ.Count; i++)
                    {
                        //Answer a = new Answer();
                        question.PossibleAnswers.Add(new PossibleAnswer { Body = answ[i], IsRight = answRight[i] });

                    }
                }
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        if (file != null)
                        {
                            MemoryStream ms = new MemoryStream();
                            file.InputStream.CopyTo(ms);
                            question.Images.Add(new Image
                            {
                                //ImageId = Guid.NewGuid(),
                                ImageBinary = ms.GetBuffer(),
                                ImageLength = file.ContentLength,
                                ImageName = file.FileName,
                                ImageType = file.ContentType
                            });

                        }
                    }
                }

                //foreach (var p in question.PossibleAnswers)
                //{
                //    p.Answers.Add(new Answer());
                //}
                TempData["message_success"] = "Вопрос успешно создан!";
                db.Questions.Add(question);
                //ans_cnt.AnswCount = question.PossibleAnswers.Count;
                db.SaveChanges();
                return RedirectToAction("CreateQuestionAndTests", "Tests");
            }
            //if (ch == false)
            //{
            //    ViewBag.Message = "Введите правильный вариант свободного ответа!";
            //}
            return View(question);
        }



        public FileContentResult OutputImage(int id)
        {

            Image image = db.Images.SingleOrDefault(f => f.ImageId == id);
            return File(image.ImageBinary, image.ImageType);

        }
        //Matrix
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create_with_matrix(Matrix matrix, List<List<string>> elements, List<List<string>> correct_elements, List<string> answ, string answrad, List<bool> CorrAnsw, string[] checkedValues, int theme_id)
        {
            bool ch = ((CorrAnsw[0] == true) == (matrix.Question.CorrectAnswer.Body != null)) && ((CorrAnsw[0] == false) == (matrix.Question.CorrectAnswer.Body == null));
            bool chform = (matrix.Question.HasPossibleAnswer != false) || (CorrAnsw[0] != false || (matrix.Question.MatrixAnswer != false));
            bool chradORbox = (matrix.Question.HasPossibleAnswer == false) || ((matrix.Question.HasPossibleAnswer == true) && ((matrix.Question.RadioAnswer != false) || (matrix.Question.CheckBoxAnswer != false)));
            if (db.Structures.ToList().Count() != 0) ViewBag.structs = db.Structures.ToList();
            var th = db.Themes.Find(theme_id);
            matrix.Question.Theme = th;
            matrix.Question.Title = th.Name;
            if (ModelState.IsValid && ch && chform && chradORbox)
            {
                MemoryStream ms = new MemoryStream();

CSOK/Views/Questions/Create.cshtml

@model CSOK.Models.Question

@{
    ViewBag.Title = "Создание вопроса";
}


@*@Html.ActionLink(User.Identity.Name, "Manage", "Account")*@
  
<link rel="stylesheet" href="~/Content/jquery.confirmon.css">

<script src="~/Scripts/jquery.confirmon.js"></script>
<script src="/Scripts/slider.js"></script>
<script src="~/Scripts/structures&themes.js"></script>
<script src="~/Scripts/jquery.nicefileinput.min.js"></script>
@* классные подсказки с эффектами ниже! *@
<script>
    $(function () {
        $('.toolTip').tooltip({
            position: {
                my: "center+5 bottom-6",
                at: "center top",
                using: function (position, feedback) {
                    $(this).css(position);
                    $("<div>")
                      .addClass("arrow")
                      .addClass(feedback.vertical)
                      .addClass(feedback.horizontal)
                      .appendTo(this);
                }
            }
        });
    });

    
</script>

@using (Html.BeginForm("Create", "Questions", FormMethod.Post, new { enctype = "multipart/form-data", id = "question_createform" }))
{
    //Html.ValidationSummary()
     <div class="top_cont3"></div> 
    
    
    <div class="top_cont_question_create"> 
@*        <legend>Вопросы</legend>*@
       
     
        <div id="structures">
            @Html.LabelFor(model => model.Title, "Укажите раздел:")
            <label for="struct_id" generated="true" class="error"></label>
       @*@Html.DropDownList("name", ViewBag.structs as SelectList , "Выберите раздел ", new { style="width:30%", @id="struct_id"})*@
            <select id="struct_id"  name="struct_id">
                <option value="">Выберите раздел</option>
            @if(ViewBag.structs != null){
            foreach (var st in ViewBag.structs)
            {
                <option value="@st.Id">@st.Name</option>
            }
            }
                else{
                <option value="0">Не найдено ни одного раздела!</option>
            }
                </select>
            @*@Html.ValidationMessageFor(model => model.Title)*@
        </div>
        <br />
        <div id="themes" hidden>
            <label for="theme">Укажите тему:</label>
            <label for="theme_id" generated="true" class="error"></label>
            <select id="theme_id" name="theme_id" >
                @*<option value="">Выберите тему вопроса</option>*@
            </select>
        </div>
        <br />
        <div class="editor-lable">
            @Html.LabelFor(model => model.Body, "Вопрос")
            <label for="Body" generated="true" class="error"></label>
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @*@Html.ValidationMessageFor(model => model.Body)*@
        </div>
         
        <fieldset id="test_setting">
            <legend>Настройки вопроса</legend>
        
           <label id="qtype21">
               <input type="checkbox" id="qtype2"  />   Прикрепить изображение к вопросу <span class="toolTip" title="Вы можете прикрепить до 5 изображений к одному вопросу">&nbsp;</span></label>
      <br />
            <div class="Images" hidden> 
    
    <input type="file" multiple="multiple" name="files" id="files" class="nice_file" />
                <br />
                <label for="files" class="error" generated="true"></label>
    </div>

            <label id="qtype31">
       @*<h3><font color="red"> @ViewBag.Message</font></h3>*@
        @Html.CheckBox("CorrAnsw", new { id ="qtype3" }) Вопрос со свободной формой <span class="toolTip" title="Ответ на вопрос будет содержать свободную формулировку">&nbsp;</span></label>
            <label for="CorrAnsw" class="error" generated="true"></label>
            
      <div class="CorrectAnswer" hidden>
          
        @Html.TextBoxFor(m => m.CorrectAnswer.Body, new { name="CorrectAnswerBody"}) <label for="CorrectAnswer_Body" class="error" generated="true"></label> Правильный ответ на вопрос со свободной формой ответа
       
    </div>
          <br /> 
        
        <label id="qtype11">
        @Html.CheckBoxFor(m => m.HasPossibleAnswer, new {  id = "qtype1" })
            Вопрос с вариантами ответа <span class="toolTip" title="Если флажок установлен, то данный вопрос будет иметь только возможные варианты ответа. Если не установлен- вопрос со свободным ответом">&nbsp;</span>
        </label>
            <label for="HasPossibleAnswer" class="error" generated="true"></label>
           <br />

            <div class="PossibleAnswer" display: none; hidden>
            Укажите форму вариантов ответа: <br />

           <label id="qtype51"> @Html.CheckBoxFor(m => m.CheckBoxAnswer, new {  id = "qtype5" })  Несколько правильных ответов <span class="toolTip" title="Чекбоксы">&nbsp;</span></label>
                <label for="CheckBoxAnswer" class="error" generated="true"></label>
          <br />
          <label id="qtype61">  @Html.CheckBoxFor(m => m.RadioAnswer, new {  id = "qtype6" }) Один правильный ответ <span class="toolTip" title="Радиокнопки">&nbsp;</span></label>
                <label for="RadioAnswer" class="error" generated="true"></label>
                 <br />
                
        <br />
            <input type="button" class="button_back" style="color:#0fc0ff" onclick="add_input()" value="Добавить еще один вариант ответа" disabled="disabled" id="addinput">
            <input type="button" class="button_back" style="color:#0fc0ff" onclick="del_input()" value="Убрать лишний вариант ответа" disabled="disabled" id="delinput">
                <label id="for_answ" class="error"></label>
            <div id="PossibleAnswers" display: none; hidden>  </div>
            </div>
       
            
        <p>
  <label for="amount">Укажите сложность вопроса:</label>
  @*<input type="number" id="amount" style="border:0; color:#f6931f; font-weight:bold;" >*@
            @Html.TextBoxFor(m => m.difficulty, new { id = "amount", @style = "border:0; color:#f6931f; font-weight:bold;" })
</p>
 
<div id="slider-range-min" style="width:500px; left:10px;"></div>
        
            </fieldset>
      
            <div id="create_button">
            <input type="submit" value="Создать вопрос" class="button_test" id="create_question" />
                </div>
       
         <div id="button_back">
@Html.ActionLink("Назад", "Index", null, new {@class="button_back" })
    </div>
        </div> 

}

@section Scripts {
@Scripts.Render("~/scripts/QuestionCreate.js")
@*@Scripts.Render("~/scripts/tooltip.js")*@
@Scripts.Render("~/scripts/checkORradio.js")
@Scripts.Render("~/scripts/jquery.validate.js")
@Scripts.Render("~/scripts/Valid.js")
@Scripts.Render("~/scripts/jquery.validation.additional-methods.js")
@Scripts.Render("~/scripts/focus.js")
@*@Scripts.Render("~/scripts/jquery.customSelect.js")*@
@Scripts.Render("~/scripts/fancySelect.js")
    }
<script type="text/javascript">
    $('input[type=file]').change(function () {
        $(this).blur();
    });
    $("input[type=file]").nicefileinput({
        label: "Выберите файл"
    });
    $('#Body').jqte();
    
    $('#create_question').confirmOn({

        questionText: 'Вы действительно хотите создать данный вопрос?', // The confirmation question
        //classPrepend: 'confirmon', // Use another prefix for the classes used by the plugin
        textYes: 'Да', // Text on the button the user clicks when the handler should be called 
        textNo: 'Нет' // Text on the button the user clicks when the handler should not be called
    },
        "click", function (e, confirmed) {
            if (confirmed) {
                if ($('#qtype5, #qtype6').is(':checked') && $('.answ').length == 0) {
                    $('#addinput, #delinput').addClass('button_error');
                    $('#for_answ').show().html("Создайте варианты ответа на вопрос");
                }
                else {
                    $('#question_createform').submit();
                }
            }
        });
</script>



@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"
    type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"
    type="text/javascript"></script>*@






CSOK/Views/Questions/CreateBlock.cshtml
@model CSOK.Models.Question

@{
    ViewBag.Title = "Создание вопроса с блоками";
}

@*<h2>Create</h2>*@

<link rel="stylesheet" href="~/Content/jquery.confirmon.css">
<script src="~/Scripts/jquery.confirmon.js"></script>
<script src="/Scripts/Valid.js"></script>
<script src="/Scripts/slider.js"></script>
<script src="~/Scripts/structures&themes.js"></script>

<script>
    $(function () {
        $('.toolTip').tooltip({
            position: {
                my: "center+5 bottom-6",
                at: "center top",
                using: function (position, feedback) {
                    $(this).css(position);
                    $("<div>")
                      .addClass("arrow")
                      .addClass(feedback.vertical)
                      .addClass(feedback.horizontal)
                      .appendTo(this);
                }
            }
        });
    });

</script>
@using (Html.BeginForm("CreateBlock", "Questions", FormMethod.Post, new { id="question_createform"}))
{
    @Html.ValidationSummary()

     <div class="top_cont3"></div>
    
    <div class="top_cont_question_create"> 

@*        <legend>Блоки</legend>*@
        <h3><font color="red"> @ViewBag.Message</font></h3>
        <div class="editor-field">
            @Html.LabelFor(model => model.Title, "Укажите раздел:")
            <label for="struct_id" generated="true" class="error"></label>
       @*@Html.DropDownList("name", ViewBag.structs as SelectList , "Выберите раздел ", new { style="width:30%", @id="struct_id"})*@
            <select id="struct_id"  name="struct_id">
                <option value="">Выберите раздел</option>
            
            @if(ViewBag.structs != null){
            foreach (var st in ViewBag.structs)
            {
                <option value="@st.Id">@st.Name</option>
            }
            }
                else{
                <option value="0">Не найдено ни одного раздела!</option>
            }
                </select>
            @*@Html.ValidationMessageFor(model => model.Title)*@
        </div>
        <br />
        <div id="themes" hidden>
            <label for="theme">Выберите тему:</label>
            <label for="theme_id" generated="true" class="error"></label>
            <select id="theme_id" name="theme_id" >
                
            </select>
        </div>
        <br />
        <div class="editor-lable">
            @Html.LabelFor(model => model.Body, "Вопрос")
            <label for="Body" generated="true" class="error"></label>
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @*@Html.ValidationMessageFor(model => model.Body, "*")*@
        </div>
        <fieldset id="test_setting">
            <legend>Настройки вопрсоа</legend>
        
        <label id="simple">
        <input type="checkbox" id="simple_blocks" name="simple_blocks"/> Обычная сортировка блоков
            <span class="toolTip" title="Студент будет сортировать блоки в правильном порядке">&nbsp;</span></label> 
            <label for="simple_blocks" class="error" generated="true"></label>
        <br />
        <label id="delete">
            @Html.CheckBoxFor(m => m.HasExcessBlocks, new { id="delete_blocks"}) Сортировка блоков с удалением лишних
            <span class="toolTip" title="Студент будет сортировать блоки в правильном порядке и удалять лишние блоки">&nbsp;</span></label> 
        <label>
           <label for="HasExcessBlocks" class="error" generated="true"></label>
        </label><ul>
            <div class="PossibleAnswers" disply: none>
            <input type="button" class="button_back" style="color:#0fc0ff" onclick="add_input()" value="Добавить еще один блок" disabled="disabled" id="addinput">
            <input type="button" class="button_back" style="color:#0fc0ff" onclick="del_input()" value="Убрать лишний блок" disabled="disabled" id="delinput"> <span class="toolTip" title="В текстовых полях блоков введите некоторое выражение">&nbsp;</span>
                <label id="for_block" class="error"></label>
            <div id="PossibleAnswers" display: none; hidden>  </div>

            </div>
        </ul>
         <p>
  <label for="amount">Укажите сложность вопроса:</label>
  @*<input type="number" id="amount" style="border:0; color:#f6931f; font-weight:bold;" >*@
            @Html.TextBoxFor(m => m.difficulty, new { id = "amount", @style = "border:0; color:#f6931f; font-weight:bold;" })
</p>
 
<div id="slider-range-min" style="width:500px; left:10px;"></div>
            </fieldset>
      <div id="create_button">
            
            <input type="submit" value="Создать вопрос" class="button_test" id="create_question"/>
          </div>
        <div id="button_back">
          @Html.ActionLink("Назад", "Index", null, new {@class="button_back" })
      </div>
   </div>
}


@section Scripts {
@Scripts.Render("~/scripts/QuestionCreate.js")
@*@Scripts.Render("~/scripts/tooltip.js")*@
    @Scripts.Render("~/scripts/block_or_excessblock.js")
@Scripts.Render("~/scripts/jquery.validate.js")
@Scripts.Render("~/scripts/focus.js")
@*@Scripts.Render("~/scripts/jquery.customSelect.js")*@
@Scripts.Render("~/scripts/fancySelect.js")
    }
<script type="text/javascript">
    $('#Body').jqte();
    $('#create_question').confirmOn({

        questionText: 'Вы действительно хотите создать данный вопрос?', // The confirmation question
        //classPrepend: 'confirmon', // Use another prefix for the classes used by the plugin
        textYes: 'Да', // Text on the button the user clicks when the handler should be called 
        textNo: 'Нет' // Text on the button the user clicks when the handler should not be called
    },
        "click", function (e, confirmed) {
            if (confirmed) {
                if ($('#simple_blocks, #delete_blocks').is(':checked') && $('.block').length == 0) {
                    $('#addinput, #delinput').addClass('button_error');
                    $('#for_block').show().html("Создайте блоки");
                }
                else {
                    $('#question_createform').submit();
                }
            }
        });
</script>

CSOK/Views/Questions/Delete.cshtml
@model CSOK.Models.Question

@{
    Layout = null;
    ViewBag.Title = "Delete";
}
<script src="/Scripts/Valid.js"></script>


<h3>Вы действительно хотите удалить этот вопрос?</h3>
@*<fieldset>
    <a class="close" onclick="close_popup();">Close</a>
    <legend>Question</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreationDataTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreationDataTime)
    </div>
</fieldset>*@

@using (Html.BeginForm()) {
    
        <input type="submit" value="Удалить" class="create_button" /> 
        
   
}

CSOK/Views/Questions/IndexBlock.cshtml

@model CSOK.Models.Question

@{
    ViewBag.Title = "CreateBlock";
}


  <style>
  #sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
  #sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
  #sortable li span { position: absolute; margin-left: -1.3em; }
  </style>
<p>
        Тема:
            @Model.Title
        <br />
            Вопрос:
            @Model.Body
<br />
   </p>   
<h3>Выберите правильное расположение блоков (сверху-вниз):</h3>
<br />
<ul id="sortable">
    
   @* @foreach (string item in Model.Blocks)*@
    @for (int i = 0; i < Model.Blocks.Count(); i++)
                {
  @*<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>@item</li>*@
        <li class="ui-state-default"> @Html.HiddenFor(x => Model.Blocks[i].ID ,new {@class = "id" }) <span>@Model.Blocks[i].Body</span></li>
    }
</ul>
<p>
            
            <input type="submit" value="Save" />
        </p>
 

 
@Html.ActionLink("Вернуться на главную", "Index")
  


@section Scripts {
   
    @Scripts.Render("~/Scripts/SortQuestion.js")
    }