CSOK/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CSOK.Models
{
    /// <summary>
    /// Класс для одного сообщения в БД
    /// </summary>
    public class Message
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public DateTime TimeSend { get; set; }
        public virtual List<UserMessage> UserMessages { get; set; } 
        public virtual List<MessageAttachment> MessageAttachments { get; set; }
        //public Message()
        //{
        //    UserMessages = new List<UserMessage>();
        //    MessageAttachments = new List<MessageAttachment>();
        //}
    }

    /// <summary>
    /// Класс для хранения в БД информации о связи пользователя с конкретным сообщением
    /// </summary>
    public class UserMessage
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserMessageId { get; set; }
        public int UserId { get; set; }
        public bool AreSender { get; set; }
        [DefaultValue(false)]
        public bool AreDeleted { get; set; }
        public DateTime? DeletedTime { get; set; }
        [DefaultValue(false)]
        public bool AreRead { get; set; }
    }

    public class MessageAttachment
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string AttachmentUrl { get; set; }
    }

    public class SendMailModel
    {
        public string To { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public List<HttpPostedFileBase> AttachmentUrls { get; set; }

        public SendMailModel()
        {
            AttachmentUrls = new List<HttpPostedFileBase>();
        }
    }

    public class MessageSummuryModel
    {
        public List<string> To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public List<string> AttachmentUrls { get; set; }
        public bool CanDelete { get; set; }
        public DateTime SendTime { get; set; }
        public DateTime? DeleteTime { get; set; }
        public int Id { get; set; }
        public bool IsInbox { get; set; }
        public string Text { get; set; }
        public bool AreRead { get; set; }
    }
}

CSOK/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using CSOK.Core;
using CSOK.Filters;
using CSOK.Models;
using WebGrease.Css.Extensions;
using WebMatrix.WebData;

namespace CSOK.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private MessageCore _core;
        public ActionResult Inbox()
        {
            ViewBag.Title = "Входящие";
            ViewBag.Type = "inbox";
            return View("MessageList");
        }

        public ActionResult Sending()
        {
            ViewBag.Title = "Исходящие";
            ViewBag.Type = "sending";
            return View("MessageList");
        }

        public ActionResult Removed(string searchString = "", int start = 0, int count = 10)
        {
            ViewBag.Title = "Удаленные";
            ViewBag.Type = "removed";
            return View("MessageList");
        }

        public ActionResult MessageListPartial(string type, string searchString = "", int start = 0, int count = 10, 
            MessageSortOrder sortOrder = MessageSortOrder.DateDesc)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            var filter = new MessageFilter();
            if (type.Equals("inbox", StringComparison.InvariantCultureIgnoreCase))
            {
                filter = new MessageFilter
                {
                    WithInbox = true,
                    WithOutbox = false,
                    AreDeleted = false
                };
            }
            if (type.Equals("sending", StringComparison.InvariantCultureIgnoreCase))
            {
                filter = new MessageFilter
                {
                    WithInbox = false,
                    WithOutbox = true,
                    AreDeleted = false
                };
            }
            if (type.Equals("removed", StringComparison.InvariantCultureIgnoreCase))
            {
                filter = new MessageFilter
                {
                    WithInbox = true,
                    WithOutbox = true,
                    AreDeleted = true
                };
            }
            filter.SearchString = searchString;
            filter.StartIndex = start;
            filter.ItemCount = count;
            filter.SortOrder = sortOrder;
            return View("pMessageList", _core.GetFilteredMessageList(filter).ToList());
        }
        public JsonResult GetPeopleVariant(string query)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            var suggestions = _core.SearchUser(query);
            if (suggestions.Count == 0)
                suggestions.Add("Нет таких пользователей");
            var q = new JsonResult
            {
                Data = new
                {
                    suggestions
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            return q;
        }
        public ActionResult Send(int? idRe)
        {
            if (idRe == null)
            {
                return View(new SendMailModel
                {
                    AttachmentUrls = new List<HttpPostedFileBase>(),
                    Subject = "",
                    Text = "",
                    To = ""
                });
            }
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            return View(_core.GetRe(idRe.Value));
        }
        [HttpPost]
        public JsonResult CheckValidName(string names)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            var badNames = _core.GetBadNames(names);
            return new JsonResult { Data = new { badNames = badNames } };
        }
        [HttpPost]
        public ActionResult SendMessage(SendMailModel model)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            _core.SendMessage(model, Server.MapPath(ConfigurationManager.AppSettings["UploadUrl"]));
            return View("SendSuccesfull");
        }

        public ActionResult Read(int id = -1)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            try
            {
                return View(_core.GetMessageById(id));
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
        [HttpPost]
        public JsonResult Delete(int id)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            _core.RemoveMessage(id);
            return new JsonResult{Data = new{ ok="ok"}};
        }

        [HttpPost]
        public JsonResult Restore(int id)
        {
            _core = new MessageCore(User.Identity.Name, (new UsersContext()).Users);
            _core.RestoreMessage(id);
            return new JsonResult { Data = new { ok = "ok" } };
        }
        ////я не смог пробиться сквозь валидацию регистрации, считерил
        private void AddUser(RegisterModel model)
        {
            var _dbContext = new MyDbContext();
            WebSecurity.CreateUserAndAccount(model.UserName, model.Password, new { Email = model.Email });
            WebSecurity.Login(model.UserName, model.Password);
            int id = WebSecurity.GetUserId(model.UserName);
            if (model.Num_of_group == null)
            {
                Teacher teacher = new Teacher();
                teacher.Name = model.Name;
                int num = Convert.ToInt32(model.Num_of_sub_faculty);
                //SubFaculty sf = (from subf in _dbContext.SubFaculties
                //                 where subf.Id == num
                //                 select subf).First();
                //teacher.SubFaculty = sf; 
                teacher.Post = model.Post;
                teacher.Rank = model.Rank;
                teacher.YOB = model.YOB;
                teacher.UserId = id;
                _dbContext.Teachers.Add(teacher);
                _dbContext.SaveChanges();
            }
            else
            {
                Student student = new Student();
                student.Num_of_record_book = model.Num_of_record_book;
                student.Name = model.Name;
                student.YOB = model.YOB.Date;
                //student.Num_of_sub_faculty = Convert.ToInt32(model.Num_of_sub_faculty);
                //CSOK.Models.Group gr = (from groupp in _dbContext.Groups
                //            where groupp.GroupName == model.Num_of_group
                //            select groupp).First();
                student.Group = _dbContext.Groups.FirstOrDefault();
                student.UserId = id;
                _dbContext.Students.Add(student);
                _dbContext.SaveChanges();
            }
            _dbContext.Dispose();
        }
        [AllowAnonymous]
        public ActionResult AddTestUser()
        {
            AddUser(new RegisterModel
            {
                UserName = "student4",
                Password = "qwerty123",
                Email = "mailStudent1@mail.ru",
                Name = "Петров Иван Сидорович",
                Num_of_record_book = "3",
                Num_of_sub_faculty = "33",
                Num_of_group = "K8-221",
                Post = "PostStudent1",
                Rank = "RankStudent1",
                YOB = new DateTime(2010, 01, 01)
            });
            //AddUser(new RegisterModel
            //{
            //    UserName = "prepod2",
            //    Password = "qwerty123",
            //    Email = "mailStudent2@mail.ru",
            //    Name = "NamePrepod2",
            //    Num_of_sub_faculty = "3",
            //    Post = "PostPrepod2",
            //    Rank = "RankPrepod2",
            //    YOB = new DateTime(2010, 01, 01)
            //});
            return View("Inbox");
        }
    }
}

CSOK/Views/Message/MessageList.cshtml
@using System.Globalization
@{
    Layout = "_MessageLayout.cshtml";
}
<script>
    whereWe = "@ViewBag.Type";
</script>
<h2>@ViewBag.Title</h2>
<div class="text-input wfull">
    <input type="text" id="searchInput" placeholder="Поиск по теме письма" style="width:700px;" 
           onkeyup="if (event.keyCode==13) listSearch();"/>
    <button type="button" onclick="listSearch()" class="btn btn-primary">Поиск</button>
</div>
<div style="clear:both"></div>
<button style="margin:10px 0" onclick="sortOrder = sortOrder == 2 ? 1 : 2;listSearch();"  class="btn btn-primary" id="sortLink">Сначала ранние</button>
<div class="message-list">
    @Html.Action("MessageListPartial","Message",new {type=ViewBag.Type})
</div>
<button onclick="doMore();" id="more" class="btn btn-primary">Больше писем!</button>

CSOK/Views/Message/Read.cshtml
@using System.Configuration
@model CSOK.Models.MessageSummuryModel
@{
    ViewBag.Title = "Read";
    Layout = "_MessageLayout.cshtml";
}
От: @Model.From <a href="/Message/Send?idRe=@Model.Id">Ответить</a><br/>
Кому: @Model.To.Aggregate((a, b) => a + "; " + b)<br/>
Содержимое:<br/> @(new MvcHtmlString(Model.Text))
<br />Вложения: 
@foreach (var file in Model.AttachmentUrls)
{
    <a href="@(ConfigurationManager.AppSettings["UploadUrl"]+file)" target="blank">@file</a>
}

CSOK/Views/Message/Send.cshtml
@model CSOK.Models.SendMailModel
@{
    ViewBag.Title = "Send";
    Layout = "_MessageLayout.cshtml";
}

<script src="/Scripts/Message.js"></script>
<script src="/Scripts/jquery.autocomplete.min.js"></script>
<script>
    $(document).ready(function ()
    {
        $('#MailTo').autocomplete({
            serviceUrl: '/message/GetPeopleVariant', // Страница для обработки запросов автозаполнения
            minChars: 1, // Минимальная длина запроса для срабатывания автозаполнения
            delimiter: /(((;)\s?)|\s)/, // Разделитель для нескольких запросов, символ или регулярное выражение
            maxHeight: 400, // Максимальная высота списка подсказок, в пикселях
            width: 300, // Ширина списка
            zIndex: 9999, // z-index списка
            deferRequestBy: 0, // Задержка запроса (мсек), на случай, если мы не хотим слать миллион запросов, пока пользователь печатает. Я обычно ставлю 300.
            onSelect: function (data, value)
            {
                $(this).val($(this).val() + "; ");
                var list = $(this).val().split(";");
                console.log(list);
            }, // Callback функция, срабатывающая на выбор одного из предложенных вариантов,
        });
    });
</script>
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post, new { enctype = "multipart/form-data", id="sendMessageForm" }))
{
    <div class="mail-send-left">Кому:</div>
    <div class="mail-send-right mail-to">
        <div class="text-input">
            @Html.TextBoxFor(x => x.To, new { id = "MailTo", onfocus="$(this).parent().css('border-color','#000000');", 
                placeholder="" })
        </div>
    </div>
    <div class="mail-send-left">Тема:</div>
    <div class="mail-send-right">
        <div class="text-input">
            @Html.TextBoxFor(x => x.Subject)
        </div>
    </div>
    <div class="mail-send-left">Текст:</div>
    <div class="mail-send-right big">
        <div class="text-input big">
            @Html.TextAreaFor(x => x.Text)
        </div>
    </div>
    <div style="clear: both;"></div>
    <div class="attachmentList" id="attachmentList">
    </div>
    <button id="addAttachmentButton" value="add" type="button" onclick="addAttachment()" class="btn btn-primary">Добавить вложение</button>
    <br /><button type="button" onclick="submitForm()" class="message-submit btn btn-primary">Отправить</button>
}

CSOK/Views/Message/SendSuccesfull.cshtml
@{
    ViewBag.Title = "SendSuccesfull";
    Layout = "_MessageLayout.cshtml";
}

<h2>Сообщение отправлено!</h2>
<a href="/Message/Inbox">Перейти во вкладку "Входящие"</a>

CSOK/Views/Message/_MessageLayout.cshtml
@{
    ViewBag.Title = "";
    Layout = "../Shared/_Layout.cshtml";
}
@*@Scripts.Render("~/Scripts/Message.js") чето-не так *@
<script src="/Scripts/Message.js"></script>
<link rel="stylesheet" href="/Content/Message.css"/>
@*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@

<div style="clear:both;"></div>
<div style="">
    <ul class="nav nav-pills" id="messageMenu">
        <li><a href="/Message/Send">Новое сообщение</a></li>
        <li><a href="/Message/Inbox">Входящие</a></li>
        <li><a href="/Message/Sending">Исходящие</a></li>
        <li><a href="/Message/Removed">Корзина</a></li>
    </ul>
    <script> $("#messageMenu li").each(function(i, v) {if ((location.href+'q').indexOf($(v).find('a').attr('href')+'q')>-1) $(v).addClass("active");});</script>
    <div style="clear:both;"></div>
@*<div class="mail-menu-left">
    <a href="/Message/Send" class="mail-menu-left-item">Новое сообщение</a>
    <a href="/Message/Inbox" class="mail-menu-left-item">Входящие</a>
    <a href="/Message/Sending" class="mail-menu-left-item">Исходящие</a>
    <a href="/Message/Removed" class="mail-menu-left-item">Корзина</a>
</div>*@
<div class="mail-center">
    @RenderBody()
</div>
    </div>
<div style="clear:both"></div>

CSOK/Views/Message/pMessageList.cshtml
@{
    Layout = null;
}
@using System.Globalization
@model List<CSOK.Models.MessageSummuryModel>
@foreach (var message in Model)
    {
        <div class="message-list-item @(message.AreRead ? "" : "new-message")" id="message-@message.Id">
            <div class="sendTime">@message.SendTime.ToString(CultureInfo.CurrentCulture)</div>
            <div class="target-email">
                @if (message.IsInbox)
                {
                    <span>От: @message.From</span>
                }
                else
                {
                    <span>Кому: @message.To.Aggregate((a, b) => a + "; " + b)</span>
                }
            </div>
            <a class="subject" href="/message/read?id=@message.Id">@message.Subject</a>
            @if (message.CanDelete)
            {
                <button type="button" class="btn btn-primary" style="float:right; margin-right:34px;" onclick=" removeMessage(@message.Id); ">Удалить</button>
            }
            else
            {
                <button type="button" class="btn btn-primary" style="float:right; margin-right:34px;" onclick=" restoreMessage(@message.Id); ">Восстановить</button>
            }
        </div>
    }
